import { QrCode, User, Activity, AlertTriangle, FileText, Stethoscope, CheckCircle2 } from 'lucide-react';
import { Logo } from './Logo';

export interface ReportRecord {
  id?: string;
  patientName: string;
  patientId: string;
  createdAt: string;
  input: {
    age: number;
    sex: number;
    trestbps: number;
    chol: number;
    fbs: number;
    thalach: number;
    cp: number;
    restecg: number;
    exang: number;
    oldpeak: number;
    slope: number;
    ca: number;
    thal: number;
  };
  probability: number;
  riskLevel: string;
  confidence: number;
  explanation: Array<{ feature: string; impact: number }>;
  recommendations: string[];
}

interface ReportTemplateProps {
  records: ReportRecord[];
  user: any;
}

export function ReportTemplate({ records, user }: ReportTemplateProps) {
  if (!records || records.length === 0) return null;

  return (
    <div className="print-only hidden w-full bg-white text-slate-900 font-sans relative">
      {records.map((record, index) => {
        const submittedInputs = record.input;
        const result = record;
        
        return (
          <div key={record.id || index} className="w-[210mm] min-h-[297mm] mx-auto p-12 relative" style={{ boxSizing: 'border-box', pageBreakAfter: index === records.length - 1 ? 'auto' : 'always' }}>
            
            {/* Header */}
            <div className="flex justify-between items-start border-b-[4px] border-blue-900 pb-6 mb-8 break-inside-avoid">
              <div className="flex items-center gap-4">
                <div className="print-color-adjust-exact drop-shadow-sm">
                  <Logo className="h-12 w-12" />
                </div>
                <div>
                  <h1 className="text-3xl font-black tracking-tight text-slate-900 m-0 leading-none">CardioGuard AI</h1>
                  <p className="text-[11px] font-bold uppercase tracking-[0.2em] text-blue-600 mt-2">Explainable Heart Disease Risk Predictor</p>
                  <p className="text-[10px] font-semibold text-slate-500 mt-1">Version 2.4.1 • Enterprise Edition</p>
                </div>
              </div>
              <div className="text-right text-xs">
                <div className="inline-block p-1 border-2 border-slate-900 rounded-lg mb-2 shadow-sm">
                  <QrCode className="h-10 w-10 text-slate-900" />
                </div>
                <p className="font-bold text-[11px] uppercase tracking-wider text-slate-500 mb-0.5">Report ID</p>
                <p className="font-bold text-sm mb-2">{result.id ? result.id.toUpperCase().substring(0,8) : Math.random().toString(36).substring(2, 10).toUpperCase()}</p>
                <p className="font-bold text-[11px] uppercase tracking-wider text-slate-500 mb-0.5">Assessment Date</p>
                <p className="font-bold text-sm leading-tight">{new Date(record.createdAt).toLocaleString('en-GB', { day: 'numeric', month: 'long', year: 'numeric', hour: 'numeric', minute: '2-digit', hour12: true }).replace(', ', '\n')}</p>
              </div>
            </div>

            {/* Section 2: Patient Information */}
            <div className="mb-8 break-inside-avoid">
              <h2 className="text-[11px] font-black uppercase tracking-[0.2em] text-blue-900 border-b-2 border-blue-100 pb-2 mb-4 flex items-center gap-2">
                <User className="h-5 w-5" /> PATIENT INFORMATION
              </h2>
              <div className="grid grid-cols-4 gap-4 text-xs">
                <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 shadow-sm print-color-adjust-exact">
                  <p className="text-[9px] uppercase font-bold text-slate-500 mb-1">Patient Name</p>
                  <p className="font-bold text-sm">{record.patientName || 'Anonymous'}</p>
                </div>
                <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 shadow-sm print-color-adjust-exact">
                  <p className="text-[9px] uppercase font-bold text-slate-500 mb-1">Patient ID</p>
                  <p className="font-bold text-sm">{record.patientId || 'Not Available'}</p>
                </div>
                <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 shadow-sm print-color-adjust-exact">
                  <p className="text-[9px] uppercase font-bold text-slate-500 mb-1">Age / Gender</p>
                  <p className="font-bold text-sm">{submittedInputs.age} Years / {submittedInputs.sex === 1 ? 'Male' : 'Female'}</p>
                </div>
                <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 shadow-sm print-color-adjust-exact">
                  <p className="text-[9px] uppercase font-bold text-slate-500 mb-1">Generated By</p>
                  <p className="font-bold text-sm">{user?.role === 'doctor' ? 'Dr. ' : ''}{user?.full_name || 'Practitioner'}</p>
                </div>
              </div>
            </div>

            {/* Section 3: Clinical Measurements */}
            <div className="mb-8 break-inside-avoid">
              <h2 className="text-[11px] font-black uppercase tracking-[0.2em] text-blue-900 border-b-2 border-blue-100 pb-2 mb-4 flex items-center gap-2">
                <Activity className="h-5 w-5" /> CLINICAL MEASUREMENTS
              </h2>
              <div className="rounded-xl border border-slate-200 overflow-hidden shadow-sm">
                <table className="w-full text-xs border-collapse">
                  <thead>
                    <tr className="bg-blue-50/80 print-color-adjust-exact border-b border-slate-200 text-left">
                      <th className="py-3 px-5 font-bold uppercase tracking-wider text-[10px] text-slate-600">Parameter</th>
                      <th className="py-3 px-5 font-bold uppercase tracking-wider text-[10px] text-slate-600">Result</th>
                      <th className="py-3 px-5 font-bold uppercase tracking-wider text-[10px] text-slate-600">Normal Range</th>
                      <th className="py-3 px-5 font-bold uppercase tracking-wider text-[10px] text-slate-600 text-right">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {[
                      { label: 'Blood Pressure', value: `${submittedInputs.trestbps} mmHg`, range: '90–120', isNormal: submittedInputs.trestbps <= 120 },
                      { label: 'Cholesterol', value: `${submittedInputs.chol} mg/dL`, range: '< 200', isNormal: submittedInputs.chol < 200 },
                      { label: 'Heart Rate', value: `${submittedInputs.thalach} bpm`, range: '60–100', isNormal: submittedInputs.thalach >= 60 && submittedInputs.thalach <= 100 },
                      { label: 'Fasting Blood Sugar', value: submittedInputs.fbs === 1 ? 'Yes (>120 mg/dL)' : 'No (Normal)', range: 'No (< 120)', isNormal: submittedInputs.fbs === 0 },
                      { label: 'Chest Pain Type', value: submittedInputs.cp === 0 ? 'Typical Angina' : submittedInputs.cp === 1 ? 'Atypical Angina' : submittedInputs.cp === 2 ? 'Non-anginal Pain' : 'Asymptomatic', range: 'Asymptomatic', isNormal: submittedInputs.cp === 3 },
                      { label: 'Resting ECG', value: submittedInputs.restecg === 0 ? 'Normal' : submittedInputs.restecg === 1 ? 'ST-T Wave Abnormality' : 'Left Ventricular Hypertrophy', range: 'Normal', isNormal: submittedInputs.restecg === 0 },
                      { label: 'Exercise Induced Angina', value: submittedInputs.exang === 1 ? 'Yes' : 'No', range: 'No', isNormal: submittedInputs.exang === 0 },
                      { label: 'ST Depression (Oldpeak)', value: submittedInputs.oldpeak, range: '< 1.0', isNormal: submittedInputs.oldpeak < 1.0 },
                      { label: 'ST Slope', value: submittedInputs.slope === 0 ? 'Upsloping' : submittedInputs.slope === 1 ? 'Flat' : 'Downsloping', range: 'Upsloping', isNormal: submittedInputs.slope === 0 },
                      { label: 'Blocked Vessels (0-3)', value: submittedInputs.ca, range: '0', isNormal: submittedInputs.ca === 0 },
                      { label: 'Thalassemia', value: submittedInputs.thal === 2 ? 'Fixed Defect' : submittedInputs.thal === 3 ? 'Reversible Defect' : 'Normal', range: 'Normal', isNormal: submittedInputs.thal === 1 || submittedInputs.thal === 0 }
                    ].map((row, i) => (
                      <tr key={i} className={`border-b border-slate-100 ${i % 2 === 0 ? 'bg-white' : 'bg-slate-50/50 print-color-adjust-exact'}`}>
                        <td className="py-2.5 px-5 font-semibold text-slate-700">{row.label}</td>
                        <td className="py-2.5 px-5 font-bold">{row.value}</td>
                        <td className="py-2.5 px-5 text-slate-500 font-medium">{row.range}</td>
                        <td className="py-2.5 px-5 text-right">
                          <span className={`inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider print-color-adjust-exact border ${
                            row.isNormal ? 'bg-emerald-50 text-emerald-700 border-emerald-200' : 'bg-rose-50 text-rose-700 border-rose-200'
                          }`}>
                            {row.isNormal ? 'Normal' : 'Abnormal'}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Section 4: Predictive Risk Estimation */}
            <div className="mb-8 break-inside-avoid">
              <h2 className="text-[11px] font-black uppercase tracking-[0.2em] text-blue-900 border-b-2 border-blue-100 pb-2 mb-4 flex items-center gap-2">
                <AlertTriangle className="h-5 w-5" /> PREDICTIVE RISK ESTIMATION
              </h2>
              
              <div className={`rounded-2xl p-8 border-[3px] shadow-sm print-color-adjust-exact mb-4 flex flex-col ${
                result.riskLevel === 'High' 
                  ? 'bg-rose-50 border-rose-300 text-rose-900' 
                  : result.riskLevel === 'Moderate'
                  ? 'bg-amber-50 border-amber-300 text-amber-900'
                  : 'bg-emerald-50 border-emerald-300 text-emerald-900'
              }`}>
                <div className="flex justify-between items-start mb-6">
                  <div>
                    <p className="text-xs font-black uppercase tracking-[0.2em] opacity-70 mb-2">Overall Assessment Status</p>
                    <h3 className="text-4xl font-black tracking-tight uppercase">{result.riskLevel} RISK</h3>
                  </div>
                  <div className="text-right">
                    <p className="text-xs font-black uppercase tracking-[0.2em] opacity-70 mb-2">Risk Probability</p>
                    <h3 className="text-4xl font-black tracking-tight">{(result.probability * 100).toFixed(0)}%</h3>
                  </div>
                </div>

                {/* Progress Bar Gauge */}
                <div className="w-full bg-white/50 rounded-full h-3 mb-8 overflow-hidden border border-black/10">
                  <div 
                    className={`h-full print-color-adjust-exact ${result.riskLevel === 'High' ? 'bg-rose-600' : result.riskLevel === 'Moderate' ? 'bg-amber-500' : 'bg-emerald-500'}`} 
                    style={{ width: `${Math.round(result.probability * 100)}%` }}
                  ></div>
                </div>

                <div className="grid grid-cols-2 gap-6 border-t border-black/10 pt-6">
                  <div className="bg-white/60 p-4 rounded-xl border border-black/5 print-color-adjust-exact">
                    <p className="text-[10px] font-black uppercase tracking-wider opacity-70 mb-1 flex justify-between">
                      <span>Model Confidence Score</span>
                      <span>{(result.confidence * 100).toFixed(1)}%</span>
                    </p>
                    <div className="w-full bg-black/10 rounded-full h-1.5 mt-2 overflow-hidden">
                      <div className="bg-black/60 h-full print-color-adjust-exact" style={{ width: `${Math.round(result.confidence * 100)}%` }}></div>
                    </div>
                  </div>
                  <div className="bg-white/60 p-4 rounded-xl border border-black/5 print-color-adjust-exact">
                    <p className="text-[10px] font-black uppercase tracking-wider opacity-70 mb-1">Primary Risk Factor (SHAP)</p>
                    <p className="font-bold text-sm">
                      {result.explanation?.length ? result.explanation.reduce((prev, current) => (Math.abs(prev.impact) > Math.abs(current.impact)) ? prev : current).feature : 'Not Available'}
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Section 5: Model Interpretation & SHAP Explainability */}
            <div className="mb-8 break-inside-avoid">
              <h2 className="text-[11px] font-black uppercase tracking-[0.2em] text-blue-900 border-b-2 border-blue-100 pb-2 mb-3 flex items-center gap-2">
                <FileText className="h-5 w-5" /> MODEL INTERPRETATION & SHAP EXPLAINABILITY
              </h2>
              <div className="text-sm leading-relaxed text-slate-700 bg-slate-50 p-5 rounded-xl border border-slate-200 shadow-sm print-color-adjust-exact">
                Based on the comprehensive physiological assessment, the trained supervised machine learning model evaluated on the Cleveland Heart Disease Dataset classifies this patient profile as a <strong>{result.riskLevel} Risk</strong> for cardiovascular complications. 
                The algorithm determined a risk probability of <strong>{(result.probability * 100).toFixed(0)}%</strong> with a confidence score of <strong>{(result.confidence * 100).toFixed(1)}%</strong>.
                {result.explanation?.length > 0 && (
                  <span>
                    {' '}An automated SHAP (SHapley Additive exPlanations) analysis identified that the patient's <strong>{result.explanation.reduce((p, c) => (Math.abs(p.impact) > Math.abs(c.impact)) ? p : c).feature}</strong> contributed most significantly to pushing the risk score {result.explanation.reduce((p, c) => (Math.abs(p.impact) > Math.abs(c.impact)) ? p : c).impact >= 0 ? 'higher' : 'lower'}.
                  </span>
                )}
                {' '}Other contributing clinical indicators were weighted simultaneously by the Random Forest classifier to finalize this diagnostic prediction. This assessment relies on correlations learned from historical medical datasets and must be interpreted alongside clinical expertise.
              </div>
            </div>

            {/* Page Break for Recommendations */}
            <div className="break-before-auto break-inside-avoid mb-12 mt-12">
              <h2 className="text-[11px] font-black uppercase tracking-[0.2em] text-blue-900 border-b-2 border-blue-100 pb-2 mb-4 flex items-center gap-2">
                <Stethoscope className="h-5 w-5" /> MEDICAL RECOMMENDATIONS
              </h2>
              <div className="grid gap-4">
                {result.recommendations && result.recommendations.length > 0 ? (() => {
                  const diet = result.recommendations.filter(r => /diet|eat|food|cholesterol|sugar|weight/i.test(r));
                  const exercise = result.recommendations.filter(r => /exercise|activity|walk|heart rate|physical/i.test(r));
                  const followup = result.recommendations.filter(r => /doctor|follow|medication|consult|monitor|physician/i.test(r));
                  const lifestyle = result.recommendations.filter(r => !diet.includes(r) && !exercise.includes(r) && !followup.includes(r));
                  
                  const categories = [
                    { title: 'Diet & Nutrition', items: diet },
                    { title: 'Physical Activity', items: exercise },
                    { title: 'Medical Follow-up & Monitoring', items: followup },
                    { title: 'General Lifestyle', items: lifestyle },
                  ];

                  return categories.map((cat, i) => cat.items.length > 0 ? (
                    <div key={i} className="bg-blue-50/40 p-4 rounded-xl border border-blue-100/50 print-color-adjust-exact">
                      <h4 className="text-xs font-black uppercase tracking-wider text-blue-800 mb-3 border-b border-blue-100 pb-2">{cat.title}</h4>
                      <ul className="grid gap-2">
                        {cat.items.map((rec, j) => (
                          <li key={j} className="flex gap-3 items-start text-xs text-slate-700">
                            <CheckCircle2 className="h-4 w-4 text-blue-600 shrink-0 mt-0.5" />
                            <span className="font-semibold leading-relaxed">{rec}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  ) : null);
                })() : (
                  <div className="text-sm text-slate-500 italic p-4 bg-slate-50 rounded-xl border border-slate-200">No specific recommendations generated for this profile.</div>
                )}
              </div>
            </div>

            {/* Section 7: Disclaimer & Footer */}
            <div className="mt-20 border-t-[3px] border-slate-900 pt-6 break-inside-avoid">
              <h3 className="text-[10px] font-black uppercase tracking-widest text-slate-800 mb-2">DISCLAIMER</h3>
              <p className="text-[9px] leading-relaxed text-slate-600 text-justify font-medium mb-6">
                This report has been generated using a trained supervised machine learning model validated on the Cleveland Heart Disease Dataset and is intended for clinical decision support. 
                It must not replace professional diagnosis or treatment by a qualified healthcare provider. CardioGuard Clinical Predictive Analytics does not assume liability for clinical decisions made solely on automated statistical risk scoring. All clinical measurements must be independently verified by a licensed physician.
              </p>
              <div className="flex justify-between items-center text-[10px] font-black uppercase tracking-widest text-slate-500 border-t border-slate-200 pt-4">
                <p>CardioGuard Analytics</p>
                <p>Clinical Decision Support</p>
                <p>Confidential Medical Report</p>
                <p>Page 1</p>
              </div>
            </div>

          </div>
        );
      })}
    </div>
  );
}
